export enum NotificationEvent {
  ROOM_CAPACITY_EXCEEDED = 'ROOM_CAPACITY_EXCEEDED',
  GATE_LEFT_OPEN = 'GATE_LEFT_OPEN',
  FREQUENT_GATE_ACCESS_FOR_OTHERS = 'FREQUENT_GATE_ACCESS_FOR_OTHERS',
  ROOM_OCCUPANCY_VERIFICATION_SUGGESTED = 'ROOM_OCCUPANCY_VERIFICATION_SUGGESTED ',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  VEHICLE_UNAUTHORIZED_ACCESS = 'VEHICLE_UNAUTHORIZED_ACCESS',
}
